# Generated by Django 2.2 on 2020-01-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='', upload_to='books/file/'),
            preserve_default=False,
        ),
    ]
