# Generated by Django 2.1.3 on 2020-03-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='From',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
